use_frameworks!

platform :ios, '12.0'

target 'RRAlamofireRxAPI_Example' do
  pod 'RRAlamofireRxAPI', :path => '../'
  

  target 'RRAlamofireRxAPI_Tests' do
    inherit! :search_paths

    
  end
end
